//Generated by .NET Class Generator Tools

using APP.Credential.Domain;
using System.Data;
using System.Data.SqlClient;
using APP.Framework.Infrastructure;

namespace APP.Credential.Infrastructure
{
	public partial class MobileAppsDeviceIDDataAccess
	{

	}
}
