//Generated by .NET Class Generator Tools

using APP.Credential.Domain;
using APP.Credential.Infrastructure;
using APP.Framework.Application;

using APP.Framework.Infrastructure;

using System;

using System.Diagnostics;

namespace APP.Credential.Application
{
	[Serializable()]
	public partial class MobileAppsDeviceIDAppService


	{

	}
}
